import { useWindowDimensions, StyleSheet } from 'react-native';
import { useMemo } from 'react';

export function useDynamicStyles() {
  const { width: screenW, height: screenH } = useWindowDimensions();
  const isPortrait = screenH >= screenW;
  const isLandscape = screenW > screenH;

  return useMemo(() => {
    // Base styles that work for both orientations
    const baseStyles = {
      container: {
        flex: 1,
        position: 'relative' as const,
        backgroundColor: 'transparent',
        padding: 20,
      },
      loadingContainer: {
        flex: 1,
        justifyContent: 'center' as const,
        alignItems: 'center' as const,
        backgroundColor: '#FFDAB9',
      },
      background: {
        ...StyleSheet.absoluteFillObject,
        zIndex: 0,
      },
      foreground: {
        ...StyleSheet.absoluteFillObject,
        zIndex: 1,
        elevation: 1,
      },
      backgroundImageStyle: {
        flex: 1,
        backgroundColor: '#FFDAB9',
      },
      frameWindow: {
        overflow: 'hidden' as const,
      },
      spriteImage: {
        position: 'absolute' as const,
        left: 0,
        top: 0,
      },
      menuContainer: {
        flex: 1,
        justifyContent: 'center' as const,
        alignItems: 'center' as const,
        backgroundColor: '#73c2b9',
      },
      menuTitle: {
        fontSize: 20,
        fontWeight: 'bold' as const,
        marginBottom: 20,
        marginTop: 20,
        marginRight: 10,
        color: '#612915',
      },
      animalName: {
        fontSize: isLandscape ? 28 : 32,
        marginTop: 0,
        fontWeight: '700' as const,
        backgroundColor: 'yellow',
        paddingVertical: 12,
        paddingHorizontal: 24,
        borderRadius: 22,
        textAlign: 'center' as const,
        elevation: 3,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3,
        opacity: 0.9,
        borderWidth: 5,
        borderColor: '#FFD700',
      },
      loadingText: {
        marginTop: 10,
        fontSize: 18,
        color: '#333',
      },
    };

    if (isPortrait) {
      // Portrait styles
      return StyleSheet.create({
        ...baseStyles,
        content: {
          flex: 1,
          marginTop: 100,
          justifyContent: 'center',
          paddingBottom: 5,
        },
        animalCard: {
          alignItems: 'center',
          justifyContent: 'center',
          height: screenH * 0.25,
          overflow: 'visible',
          marginTop: 150,
        },
        animalNameWrapper: {
          position: 'absolute',
          top: -100,
          width: '100%',
          alignItems: 'center',
        },
        navButton: {
          backgroundColor: 'blue',
          paddingVertical: 8,
          paddingHorizontal: 15,
          borderRadius: 20,
          marginHorizontal: 20,
          flexDirection: 'row',
          alignItems: 'center',
          justifyContent: 'center',
          elevation: 2,
          shadowColor: '#000',
          shadowOffset: { width: 0, height: 1 },
          shadowOpacity: 0.2,
          shadowRadius: 2,
          width: 100,
          height: 60,
        },
        buttonText: {
          color: '#fff',
          fontWeight: 'bold',
          marginHorizontal: 5,
          marginTop: 40,
          marginLeft: 10,
          marginRight: 10,
          marginBottom: 10,
          height: 20,
          width: 20,
        },
        animalLoadingContainer: {
          position: 'absolute',
          justifyContent: 'center',
          alignItems: 'center',
          width: screenW * 0.5,
          height: screenH * 0.25,
        },
        soundButton: {
          position: 'absolute',
          top: 100,
          right: 20,
          backgroundColor: 'rgba(220, 173, 30, 0.7)',
          borderRadius: 25,
          padding: 10,
          zIndex: 10,
          elevation: 5,
          shadowColor: '#000',
          shadowOffset: { width: 0, height: 2 },
          shadowOpacity: 0.3,
          shadowRadius: 3,
        },
        animalImage: {
          width: screenW * 0.8,
          height: screenH * 0.3,
          resizeMode: 'contain',
          marginTop: 150,
        },
        levelGrid: {
          flexDirection: 'row',
          flexWrap: 'wrap',
          justifyContent: 'space-between',
          paddingHorizontal: 10,
        },
        levelButton: {
          borderRadius: 15,
          width: '70%',
          aspectRatio: 1,
          justifyContent: 'center',
          alignItems: 'center',
          shadowColor: '#000',
          shadowOpacity: 0.2,
          shadowRadius: 5,
          elevation: 4,
          overflow: 'hidden',
        },
        levelButtonBackground: {
          position: 'absolute',
          width: '100%',
          height: '100%',
          borderRadius: 15,
          resizeMode: 'cover',
        },
        levelText: {
          color: 'white',
          fontSize: 15,
          fontWeight: 'bold',
          textAlign: 'center',
          paddingVertical: 5,
          paddingHorizontal: 10,
          borderRadius: 20,
          overflow: 'hidden',
          marginTop: 2,
        },
        backToMenuButton: {
          backgroundColor: 'orange',
          paddingVertical: 12,
          paddingHorizontal: 20,
          borderRadius: 25,
          flexDirection: 'row',
          alignItems: 'center',
          justifyContent: 'center',
          elevation: 3,
          shadowColor: '#000',
          shadowOffset: { width: 0, height: 2 },
          shadowOpacity: 0.3,
          shadowRadius: 3,
          position: 'absolute',
          top: 50,
          left: 20,
          zIndex: 10,
        },
        instructionBubble: {
          position: 'absolute',
          left: 20,
          right: 20,
          top: 100,
          paddingVertical: 16,
          paddingHorizontal: 22,
          backgroundColor: 'white',
          borderRadius: 20,
          shadowColor: '#000',
          shadowOpacity: 0.18,
          shadowRadius: 6,
          shadowOffset: { width: 0, height: 2 },
          elevation: 6,
          zIndex: 20,
          marginBottom: 18,
          borderWidth: 2,
          borderColor: '#e0e0e0',
        },
        instructionText: {
          fontSize: 20,
          color: '#333',
          textAlign: 'center',
          marginBottom: 18,
          marginTop: 10,
          fontWeight: 'bold',
        },
      });
    } else {
      // Landscape styles - improved and more responsive
      return StyleSheet.create({
        ...baseStyles,
        container: {
          flex: 1,
          backgroundColor: 'transparent',
          padding: 15, // Reduced padding for landscape
        },
        content: {
          flex: 1,
          justifyContent: 'center',
          alignItems: 'center',
          paddingTop: 20,
          paddingBottom: 20,
        },
        animalCard: {
          alignItems: 'center',
          justifyContent: 'center',
          width: '100%',
          height: screenH * 0.6, // More responsive height
          marginTop: Math.max(20, screenH * 0.1), // Dynamic margin
        },
        animalNameWrapper: {
          position: 'absolute',
          top: -Math.max(60, screenH * 0.15), // Dynamic positioning
          width: '100%',
          alignItems: 'center',
        },
        animalImage: {
          width: Math.min(screenW * 0.4, screenH * 0.8), // Better aspect ratio
          height: screenH * 0.6,
          resizeMode: 'contain',
          marginTop: 0,
        },
        animalLoadingContainer: {
          width: Math.min(screenW * 0.4, screenH * 0.8),
          height: screenH * 0.6,
          justifyContent: 'center',
          alignItems: 'center',
        },
        soundButton: {
          position: 'absolute',
          top: 15,
          right: 15,
          backgroundColor: 'rgba(220, 173, 30, 0.7)',
          borderRadius: 25,
          padding: 10,
          zIndex: 10,
          elevation: 5,
          shadowColor: '#000',
          shadowOffset: { width: 0, height: 2 },
          shadowOpacity: 0.3,
          shadowRadius: 3,
        },
        backToMenuButton: {
          backgroundColor: 'orange',
          paddingVertical: 10,
          paddingHorizontal: 16,
          borderRadius: 25,
          flexDirection: 'row',
          alignItems: 'center',
          justifyContent: 'center',
          elevation: 3,
          shadowColor: '#000',
          shadowOffset: { width: 0, height: 2 },
          shadowOpacity: 0.3,
          shadowRadius: 3,
          position: 'absolute',
          top: 15,
          left: 15,
          zIndex: 10,
        },
        levelGrid: {
          flexDirection: 'row',
          flexWrap: 'wrap',
          justifyContent: 'space-around',
          width: '100%',
          paddingHorizontal: 20,
        },
        levelButton: {
          width: Math.min(screenW * 0.25, 120), // Max width constraint
          aspectRatio: 1,
          borderRadius: 15,
          overflow: 'hidden',
          justifyContent: 'center',
          alignItems: 'center',
          shadowColor: '#000',
          shadowOpacity: 0.2,
          shadowRadius: 5,
          elevation: 4,
          margin: 5,
        },
        levelButtonBackground: {
          position: 'absolute',
          width: '100%',
          height: '100%',
          borderRadius: 15,
          resizeMode: 'cover',
        },
        levelText: {
          color: 'white',
          fontSize: 12,
          fontWeight: 'bold',
          textAlign: 'center',
          paddingVertical: 4,
          paddingHorizontal: 8,
          borderRadius: 15,
          overflow: 'hidden',
        },
        navButton: {
          backgroundColor: 'blue',
          paddingVertical: 6,
          paddingHorizontal: 12,
          borderRadius: 20,
          marginHorizontal: 15,
          flexDirection: 'row',
          alignItems: 'center',
          justifyContent: 'center',
          elevation: 2,
          shadowColor: '#000',
          shadowOffset: { width: 0, height: 1 },
          shadowOpacity: 0.2,
          shadowRadius: 2,
          width: 80,
          height: 50,
        },
        buttonText: {
          color: '#fff',
          fontWeight: 'bold',
          fontSize: 14,
        },
        instructionBubble: {
          position: 'absolute',
          top: 20,
          left: '15%',
          right: '15%',
          paddingVertical: 12,
          paddingHorizontal: 18,
          backgroundColor: 'white',
          borderRadius: 16,
          shadowColor: '#000',
          shadowOpacity: 0.18,
          shadowRadius: 6,
          shadowOffset: { width: 0, height: 2 },
          elevation: 6,
          zIndex: 20,
          borderWidth: 2,
          borderColor: '#e0e0e0',
          marginBottom: 18,
        },
        instructionText: {
          fontSize: 16,
          color: '#333',
          textAlign: 'center',
          marginBottom: 10,
          marginTop: 5,
          fontWeight: 'bold',
        },
      });
    }
  }, [screenW, screenH, isPortrait, isLandscape]);
}

