// app/localization/strings.ts

export const strings = {
  en: {
    
      selectLevel: 'Pick your world 🐾',
      couldNotConnectToAppStore: 'Oops! Couldn’t connect to the App Store.',
      couldNotRestorePurchases: 'Hmm… could not bring back your purchases.',
      couldNotCompletePurchase: 'Uh-oh! Purchase didn’t go through.',
      farm: 'Happy Farm',
      forest: 'Magic Forest',
      ocean: 'Ocean Adventure',
      desert: 'Sunny Desert',
      arctic: 'Chilly Arctic',
      insects: 'Bug World',
      savannah: 'Warm Savannah',
      jungle: 'Mysterious Jungle',
      birds: 'Bird Paradise',
      locked: 'Locked 🔒',
      tapToHear: 'Tap a critter to hear its voice!',
      unlockLevel: 'Unlock Mission',
      unlockMessage: 'To open this mission, get {level} and join the fun!',
      appStorePay: 'Get it now',
      googlePlayPay: 'Get it now',
      backgroundNotAvailable: 'Background is hiding for this mission.',
      noAnimalsForLevel: 'No animal friends here yet.',
      tapAnimalToHearSound: 'Tap a critter to hear what it says!',
      levelFarm: 'MISSION: HAPPY FARM',
      levelForest: 'MISSION: MAGIC FOREST',
      levelOcean: 'MISSION: OCEAN ADVENTURE',
      levelDesert: 'MISSION: SUNNY DESERT',
      levelArctic: 'MISSION: CHILLY ARCTIC',
      levelInsects: 'MISSION: BUG WORLD',
      levelSavannah: 'MISSION: WARM SAVANNAH',
      levelJungle: 'MISSION: MYSTERIOUS JUNGLE',
      levelBirds: 'MISSION: BIRD PARADISE',
      unlockAllLevels: 'Unlock All Missions 🔓',
      unlockAllLevelsSale: 'Unlock All Missions - SALE! 🔓',
      unlockAllMissions: 'Unlock All Missions',
      sale: 'SALE',
      limitedSale: 'LIMITED SALE',
      save40: 'SAVE 67%',
      originalPrice: '$0.99',
      salePrice: '$0.99',
      regularUnlockPrice: '$0.99',
      salePriceDisplay: '$0.99',
      restorePurchases: 'Restore Purchases',
      processing: 'Processing...',
      loading: 'Loading...',
      volume: 'Volume',
      language: 'Language',
      
      // Parental Gate Strings
      parentalPermissionRequired: 'Parental Permission Required',
      parentalGateMessage: 'Please complete this challenge to access the store:',
      chooseChallengeType: 'Choose Challenge Type:',
      math: 'Math',
      word: 'Word',
      hold: 'Hold',
      yourAnswer: 'Your answer...',
      submit: 'Submit',
      newQuestion: 'New Question',
      holdButton: 'Hold Me!',
      holding: 'Hold...',
      holdFor3Seconds: 'Hold the button for 3 seconds',
      typeTheWord: 'Type the word:',
      incorrectAnswer: 'Incorrect Answer',
      tryAgainMessage: 'Please try again or ask a parent for help.',
      tryAgain: 'Try Again',
      settings: 'Settings',
      selectLanguage: 'Pick a Language',
      close: 'Close',
      done: 'All Done',
      thisLevelIsLocked: 'This mission is locked. Unlock them all to play!',
      unlockAllLevelsToPlay: 'Unlock All Missions To Play',
      skip: 'Skip',
      home: 'Home',
      congratulations: 'Yay! 🎉',
      youveSeenAllAnimals: 'You found all the animals here!',
      startOver: 'Start Again',
      menu: 'Menu',
      pickWorldMessage: 'Pick a world and start your adventure! 🐾',
      about: 'About the Game',
      aboutDescription: 'Ready for some giggles and fun? In this game, you’ll meet all sorts of cute animals — and hear the silly sounds they make! Just tap each one to learn their name and sound. Moo! Quack! Roar!\n\nCan you guess them all? Let’s play and learn together!',
      viewAllAnimals: 'See All Animals',
      arcticCollection: 'Arctic Friends Collection',
      animalsToDiscover: '{count} animals to discover',
      missionComplete: '🏆 Mission Complete!',
      missionNotebook: '{level} Mission!',
      resetMissionTitle: 'Are you sure?',
      resetMissionMessage: 'This will clear your progress for this mission.',
      yesReset: 'Yes, Reset It',
      resetMission: 'Reset Mission',
      animalLocked: 'Friend Locked!',
      unlockAnimalMessage: 'Go back to the mission to meet this friend first.',
      cancel: 'Cancel',
      goBack: 'Go Back',
      resetAllLevels: 'Reset All Missions',
      resetAllLevelsConfirmation: 'Are you sure you want to clear all missions? You can’t undo this.',
      reset: 'Reset',
      resetComplete: 'All Set!',
      allLevelsReset: 'All missions have been reset. Let’s start fresh!',
      error: 'Oops!',
      resetError: 'Something went wrong. Try again.',
      gameProgress: 'Your Adventure',
      thankYou: 'Thank you!',
      allLevelsNowUnlocked: 'All missions are now open!',
      purchaseError: 'Purchase Error',
      somethingWentWrong: 'Something went wrong.',
      restored: 'Restored',
      noPreviousPurchases: 'No purchases found.',
      noPurchasesFound: 'No purchases found.',
      defaultPrice: '$0.99',
      discovered: 'Discovered',
      levelDiscoveredAnimals: 'Animals',
      levelDiscoveredInsects: 'Insects',
      levelDiscoveredBirds: 'Birds',
      completeMission: 'Complete Mission',
      completeMissionCelebration: '🎉 COMPLETE MISSION! 🎉',
      sound: 'Sound',
      dragAnimalHere: 'Drag animal here',
  
  
    animals: {
      cat: 'Cat',
      chicken: 'Chicken',
      dog: 'Dog',
      donkey: 'Donkey',
      cow: 'Cow',
      chick: 'Chick',
      duck: 'Duck',
      goat: 'Goat',
      goose: 'Goose',
      horse: 'Horse',
      llama: 'Llama',
      pig: 'Pig',
      rabbit: 'Rabbit',
      rooster: 'Rooster',
      sheep: 'Sheep',
      turkey: 'Turkey',
      fox: 'Fox',
      bear: 'Bear',
      whiteBear: 'White Bear',
      whiteFox: 'White Fox',
      reindeer: 'Reindeer',
      snowyowl: 'Snow Owl',
      raccoon: 'Raccoon',
      squirrel: 'Squirrel',
      hedgehog: 'Hedgehog',
      owl: 'Owl',
      wolf: 'Wolf',
      deer: 'Deer',
      moose: 'Moose',
      mouse: 'Mouse',
      badger: 'Badger',
      koala: 'Koala',
      beaver: 'Beaver',
      boar: 'Boar',
      bat: 'Bat',
      camel: 'Camel',
      leon: 'Lion',
      crocodile: 'Crocodile',
      dolphin: 'Dolphin',
      eagle: 'Eagle',
      elephant: 'Elephant',
      flamingo: 'Flamingo',
      frog: 'Frog',
      giraffe: 'Giraffe',
      gorilla: 'Gorilla',
      hippopotamus: 'Hippopotamus',
      leopard: 'Leopard',
      lion: 'Lion',
      monkey: 'Monkey',
      octopus: 'Octopus',
      ostrich: 'Ostrich',
      otter: 'Otter',
      panda: 'Panda',
      parrot: 'Parrot',
      peacock: 'Peacock',
      pelican: 'Pelican',
      penguin: 'Penguin',
      rhinoceros: 'Rhinoceros',
      seal: 'Seal',
      shark: 'Shark',
      snake: 'Snake',
      skunk: 'Skunk',
      tiger: 'Tiger',
      turtle: 'Turtle',
      walrus: 'Walrus',
      whale: 'Whale',
      zebra: 'Zebra',
      ant: 'Ant',
      bee: 'Bee',
      beetle: 'Beetle',
      butterfly: 'Butterfly',
      cricket: 'Cricket',
      dragonfly: 'Dragonfly',
      firefly: 'Firefly',
      fly: 'Fly',
      grasshopper: 'Grasshopper',
      ladybug: 'Ladybug',
      mosquito: 'Mosquito',
      scorpion: 'Scorpion',
      snail: 'Snail',
      spider: 'Spider',
      wasp: 'Wasp',
      caracal: 'Caracal',
      desertTortoise: 'Desert Tortoise',
      fennecFox: 'Fennec Fox',
      iguana: 'Iguana',
      jackal: 'Jackal',
      jerboa: 'Jerboa',
      oryx: 'Oryx',
      sandCat: 'Sand Cat',
      antelope: 'Antelope',
      bison: 'Bison',
      gepard: 'Cheetah',
      hyena: 'Hyena',
      wildboar: 'Wild Boar',
      caterpillar: 'Caterpillar',
      cockroach: 'Cockroach',
      ladyBag: 'Ladybug',
      crab: 'Crab',
      fish: 'Fish',
      jellyfish: 'Jellyfish',
      lobster: 'Lobster',
      seaTurtle: 'Sea Turtle',
      seahorse: 'Seahorse',
      shrimp: 'Shrimp',
      starfish: 'Starfish',
      stingray: 'Stingray',
      canary: 'Canary',
      dove: 'Dove',
      raven: 'Raven',
      seagull: 'Seagull',
      sparrow: 'Sparrow',
      stork: 'Stork',
      swan: 'Swan',
      toucan: 'Toucan',
      woodpecker: 'Woodpecker',
      antEater: 'Ant Eater',
      asianElephant: 'Asian Elephant',
      bengalTiger: 'Bengal Tiger',
      blackPanther: 'Black Panther',
      capybara: 'Capybara',
      chameleon: 'Chameleon',
      cheetah: 'Cheetah',
      chimpanzee: 'Chimpanzee',
      cobra: 'Cobra',
      jaguar: 'Jaguar',
      lemur: 'Lemur',
      lynx: 'Lynx',
      meerkat: 'Meerkat',
      mantis: 'Mantis',
      worm: 'Worm',
      mongoose: 'Mongoose',
      lizard: 'Lizard',
      orangutan: 'Orangutan',
      sloth: 'Sloth',
    },
  },
  ru: {
    selectLevel: 'Выбери мир 🐾',
    couldNotConnectToAppStore: 'Ой! Не получилось подключиться к App Store.',
    couldNotRestorePurchases: 'Ой-ой! Не получилось вернуть покупки.',
    couldNotCompletePurchase: 'Упс! Покупка не завершилась.',
    farm: 'Весёлая ферма',
    forest: 'Волшебный лес',
    ocean: 'Морские приключения',
    desert: 'Солнечная пустыня',
    arctic: 'Холодная Арктика',
    insects: 'Мир насекомых',
    savannah: 'Тёплая саванна',
    jungle: 'Таинственные джунгли',
    birds: 'Птичий рай',
    locked: 'Замочек 🔒',
    tapToHear: 'Нажми на зверюшку и услышишь её голосок!',
    unlockLevel: 'Открыть миссию',
    unlockMessage: 'Чтобы открыть эту миссию, купи {level} и вперёд к приключениям!',
    appStorePay: 'Купить за 0.99$',
    googlePlayPay: 'Купить за 0.99$',
    backgroundNotAvailable: 'Фон для этой миссии пока спрятался.',
    noAnimalsForLevel: 'Зверюшки здесь пока отдыхают.',
    tapAnimalToHearSound: 'Нажми на зверюшку и послушай, что она скажет!',
    levelFarm: 'МИССИЯ: ВЕСЁЛАЯ ФЕРМА',
    levelForest: 'МИССИЯ: ВОЛШЕБНЫЙ ЛЕС',
    levelOcean: 'МИССИЯ: МОРСКИЕ ПРИКЛЮЧЕНИЯ',
    levelDesert: 'МИССИЯ: СОЛНЕЧНАЯ ПУСТЫНЯ',
    levelArctic: 'МИССИЯ: ХОЛОДНАЯ АРКТИКА',
    levelInsects: 'МИССИЯ: МИР НАСЕКОМЫХ',
    levelSavannah: 'МИССИЯ: ТЁПЛАЯ САВАННА',
    levelJungle: 'МИССИЯ: ТАИНСТВЕННЫЕ ДЖУНГЛИ',
    levelBirds: 'МИССИЯ: ПТИЧИЙ РАЙ',
    unlockAllLevels: 'Открыть все миссии 🔓',
    unlockAllLevelsSale: 'Открыть все миссии - СКИДКА! 🔓',
    unlockAllMissions: 'Открыть все миссии',
    sale: 'СКИДКА',
    limitedSale: 'ОГРАНИЧЕННАЯ СКИДКА',
    save40: 'ЭКОНОМИЯ 67%',
    originalPrice: '$0.99',
    salePrice: '$0.99',
    regularUnlockPrice: '$0.99',
    salePriceDisplay: '$0.99',
    restorePurchases: 'Вернуть покупки',
    processing: 'Обработка...',
    loading: 'Загрузка...',
    close: 'Закрыть',
    thisLevelIsLocked: 'Эта миссия под замочком. Открой все, чтобы играть!',
    unlockAllLevelsToPlay: 'Открыть все миссии 🔓',
    skip: 'Пропустить',
    home: 'Домик',
    volume: 'Громкость',
    done: 'Готово',
    language: 'Язык',
    settings: 'Настройки',
    selectLanguage: 'Выбери язык',
    congratulations: 'Ура! 🎉',
    youveSeenAllAnimals: 'Ты нашёл всех зверюшек на этом уровне!',
    startOver: 'Начать снова',
    menu: 'Меню',
    pickWorldMessage: 'Выбери мир и вперёд в приключения! 🐾',
    about: 'О игре',
    aboutDescription: 'Готов веселиться? Тут тебя ждут самые разные зверюшки и их весёлые голоса! Просто нажми на каждого зверя, чтобы услышать, как его зовут и что он скажет. Му-у! Кря! Р-р-р!\n\nСможешь угадать всех? Давай играть и учиться вместе!',
    viewAllAnimals: 'Посмотреть всех зверюшек',
    arcticCollection: 'Коллекция арктических друзей',
    animalsToDiscover: 'Ещё {count} зверюшек',
    missionComplete: '🏆 Миссия выполнена!',
    missionNotebook: 'Миссия {level}!',
    resetMissionTitle: 'Точно?',
    resetMissionMessage: 'Это сбросит весь прогресс по этой миссии.',
    yesReset: 'Да, сбросить',
    resetMission: 'Сбросить миссию',
    animalLocked: 'Зверюшка под замочком!',
    unlockAnimalMessage: 'Сначала открой её в миссии, а потом приходи сюда.',
    cancel: 'Отмена',
    goBack: 'Назад',
    resetAllLevels: 'Сбросить все миссии',
    resetAllLevelsConfirmation: 'Точно хочешь сбросить весь прогресс? Это нельзя отменить.',
    reset: 'Сбросить',
    resetComplete: 'Готово!',
    allLevelsReset: 'Все миссии снова закрыты, начинаем с нуля!',
    error: 'Ой, ошибка!',
    resetError: 'Что-то пошло не так. Попробуй ещё раз.',
    gameProgress: 'Прогресс игры',
    thankYou: 'Спасибо!',
    allLevelsNowUnlocked: 'Все миссии теперь открыты!',
    purchaseError: 'Ошибка покупки',
    somethingWentWrong: 'Что-то пошло не так.',
    restored: 'Восстановлено',
    noPreviousPurchases: 'Покупок не найдено.',
    noPurchasesFound: 'Покупок не найдено.',
    sound: 'Звук',
          defaultPrice: '$0.99',
      discovered: 'Найдено',
      levelDiscoveredAnimals: 'Зверюшек',
      levelDiscoveredInsects: 'Насекомых',
      levelDiscoveredBirds: 'Птиц',
      completeMission: 'Завершить миссию',
      completeMissionCelebration: '🎉 МИССИЯ ЗАВЕРШЕНА! 🎉',
      dragAnimalHere: 'Перетащи зверюшку сюда',
    
    // Parental Gate Strings
    parentalPermissionRequired: 'Требуется разрешение родителей',
    parentalGateMessage: 'Пожалуйста, выполните задание для доступа к магазину:',
    chooseChallengeType: 'Выберите тип задания:',
    math: 'Математика',
    word: 'Слово',
    hold: 'Удержание',
    yourAnswer: 'Ваш ответ...',
    submit: 'Отправить',
    newQuestion: 'Новый вопрос',
    holdButton: 'Держи меня!',
    holding: 'Держи...',
    holdFor3Seconds: 'Держите кнопку 3 секунды',
    typeTheWord: 'Наберите слово:',
    incorrectAnswer: 'Неверный ответ',
    tryAgainMessage: 'Попробуйте снова или попросите помощи у родителей.',
    tryAgain: 'Попробовать снова',
    
    animals: {
      cat: 'Kошка',
      chicken: 'Курица',
      dog: 'Собака',
      donkey: 'Осел',
      cow: 'Корова',
      chick: 'Цыпленок',
      duck: 'Утка',
      goat: 'Коза',
      goose: 'Гусь',
      horse: 'Лошадь',
      llama: 'Лама',
      pig: 'Свинья',
      rabbit: 'Кролик',
      rooster: 'Петух',
      sheep: 'Овца',
      koala: 'Коала',
      turkey: 'Индейка',
      fox: 'Лиса',
      bear: 'Медведь',
      whiteBear: 'Белый медведь',
      whiteFox: 'Белая лиса',
      reindeer: 'Северный олень',
      snowyowl: 'Полярная сова',
      raccoon: 'Енот',
      squirrel: 'Белка',
      hedgehog: 'Ёж',
      owl: 'Сова',
      wolf: 'Волк',
      deer: 'Олень',
      moose: 'Лось',
      mouse: 'Мышь',
      badger: 'Барсук',
      beaver: 'Бобр',
      boar: 'Кабан',
      bat: 'Летучая мышь',
      camel: 'Верблюд',
      crocodile: 'Крокодил',
      dolphin: 'Дельфин',
      eagle: 'Орел',
      elephant: 'Слон',
      flamingo: 'Фламинго',
      frog: 'Лягушка',
      giraffe: 'Жираф',
      gorilla: 'Горилла',
      hippopotamus: 'Бегемот',
      leopard: 'Леопард',
      lion: 'Лев',
      monkey: 'Обезьяна',
      octopus: 'Осьминог',
      ostrich: 'Страус',
      otter: 'Выдра',
      panda: 'Панда',
      parrot: 'Попугай',
      peacock: 'Павлин',
      pelican: 'Пеликан',
      penguin: 'Пингвин',
      rhinoceros: 'Носорог',
      seal: 'Тюлень',
      shark: 'Акула',
      snake: 'Змея',
      skunk: 'Скунс',
      tiger: 'Тигр',
      turtle: 'Черепаха',
      walrus: 'Морж',
      whale: 'Кит',
      zebra: 'Зебра',
      ant: 'Муравей',
      bee: 'Пчела',
      beetle: 'Жук',
      butterfly: 'Бабочка',
      cricket: 'Сверчок',
      dragonfly: 'Стрекоза',
      firefly: 'Светлячок',
      fly: 'Муха',
      grasshopper: 'Кузнечик',
      ladybug: 'Божья коровка',
      mosquito: 'Комар',
      scorpion: 'Скорпион',
      snail: 'Улитка',
      spider: 'Паук',
      wasp: 'Оса',
      caracal: 'Каракал',
      desertTortoise: 'Пустынная черепаха',
      fennecFox: 'Фенек',
      iguana: 'Игуана',
      jackal: 'Шакал',
      mantis: 'Мантис',
      worm: 'Червь',
      jerboa: 'Тушканчик',
      oryx: 'Орикс',
      sandCat: 'Песчаная кошка',
      antelope: 'Антилопа',
      bison: 'Бизон',
      gepard: 'Гепард',
      hyena: 'Гиена',
      wildboar: 'Дикий кабан',
      caterpillar: 'Гусеница',
      cockroach: 'Таракан',
      ladyBag: 'Божья коровка',
      crab: 'Краб',
      fish: 'Рыба',
      leon: 'Лев',
      jellyfish: 'Медуза',
      lobster: 'Омар',
      seaTurtle: 'Морская черепаха',
      seahorse: 'Морской конек',
      shrimp: 'Креветка',
      starfish: 'Морская звезда',
      stingray: 'Скат',
      canary: 'Канарейка',
      dove: 'Голубь',
      raven: 'Ворон',
      seagull: 'Чайка',
      sparrow: 'Воробей',
      stork: 'Аист',
      swan: 'Лебедь',
      toucan: 'Тукан',
      woodpecker: 'Дятел',
      antEater: 'Муравьед',
      asianElephant: 'Азиатский слон',
      bengalTiger: 'Бенгальский тигр',
      blackPanther: 'Чёрная пантера',
      capybara: 'Капибара',
      chameleon: 'Хамелеон',
      cheetah: 'Гепард',
      chimpanzee: 'Шимпанзе',
      cobra: 'Кобра',
      jaguar: 'Ягуар',
      lemur: 'Лемур',
      lynx: 'Рысь',
      meerkat: 'Сурикат',
      mongoose: 'Мангуст',
      lizard: 'Ящерица',
      orangutan: 'Орангутан',
      sloth: 'Ленивец',
    },
  },
  tr: {
    
      selectLevel: 'Dünyanı seç 🐾',
      couldNotConnectToAppStore: 'Ups! App Store’a bağlanamadık.',
      couldNotRestorePurchases: 'Hmm… Satın aldıklarını geri getiremedik.',
      couldNotCompletePurchase: 'Amanın! Satın alma tamamlanamadı.',
      farm: 'Mutlu Çiftlik',
      forest: 'Sihirli Orman',
      ocean: 'Deniz Macerası',
      desert: 'Güneşli Çöl',
      arctic: 'Buzlu Kutup',
      insects: 'Böcekler Diyarı',
      savannah: 'Sıcak Savana',
      jungle: 'Gizemli Orman',
      birds: 'Kuşlar Ülkesi',
      locked: 'Kilitli 🔒',
      tapToHear: 'Hayvan dostuna dokun, sesini duy! 🐶',
      unlockLevel: 'Görevi Aç',
      unlockMessage: '{level} görevini açmak için {price} ile katıl!',
      appStorePay: 'Hemen Al',
      googlePlayPay: 'Hemen Al',
      backgroundNotAvailable: 'Bu görevde arka plan şu an yok.',
      noAnimalsForLevel: 'Bu görevde hayvan dostlar henüz yok.',
      tapAnimalToHearSound: 'Hayvan dostuna dokun, sesini duy! 🐾',
      levelFarm: 'GÖREV: MUTLU ÇİFTLİK',
      levelForest: 'GÖREV: SİHİRLİ ORMAN',
      levelOcean: 'GÖREV: DENİZ MACERASI',
      levelDesert: 'GÖREV: GÜNEŞLİ ÇÖL',
      levelArctic: 'GÖREV: BUZLU KUTUP',
      levelInsects: 'GÖREV: BÖCEKLER DİYARI',
      levelSavannah: 'GÖREV: SICAK SAVANA',
      levelJungle: 'GÖREV: GİZEMLİ ORMAN',
      levelBirds: 'GÖREV: KUŞLAR ÜLKESİ',
      unlockAllLevels: 'Tüm Görevleri Aç 🔓',
      unlockAllLevelsSale: 'Tüm Görevleri Aç - İNDİRİM! 🔓',
      unlockAllMissions: 'Tüm Görevleri Aç',
      sale: 'İNDİRİM',
      limitedSale: 'SINIRLI İNDİRİM',
      save40: '%67 TASARRUF',
      originalPrice: '$0.99',
      salePrice: '$0.99',
      regularUnlockPrice: '$0.99',
      salePriceDisplay: '$0.99',
      restorePurchases: 'Satın Alınanları Geri Getir',
      processing: 'İşleniyor...',
      loading: 'Yükleniyor...',
      volume: 'Ses',
      done: 'Tamamdır',
      language: 'Dil',
      settings: 'Ayarlar',
      selectLanguage: 'Dilini Seç',
      
      // Parental Gate Strings
      parentalPermissionRequired: 'Ebeveyn İzni Gerekli',
      parentalGateMessage: 'Mağazaya erişmek için lütfen bu görevi tamamlayın:',
      chooseChallengeType: 'Görev Türünü Seçin:',
      math: 'Matematik',
      word: 'Kelime',
      hold: 'Basılı Tut',
      yourAnswer: 'Cevabınız...',
      submit: 'Gönder',
      newQuestion: 'Yeni Soru',
      holdButton: 'Beni Tut!',
      holding: 'Tutuyor...',
      holdFor3Seconds: 'Butonu 3 saniye basılı tutun',
      typeTheWord: 'Kelimeyi yazın:',
      incorrectAnswer: 'Yanlış Cevap',
      tryAgainMessage: 'Lütfen tekrar deneyin veya ebeveynlerinizden yardım isteyin.',
      tryAgain: 'Tekrar Dene',
      close: 'Kapat',
      thisLevelIsLocked: 'Bu görev kilitli. Oynamak için hepsini aç!',
      unlockAllLevelsToPlay: 'Tüm Görevleri Aç',
      skip: 'Geç',
      home: 'Ana Sayfa',
      congratulations: 'Yaşasın! 🎉',
      youveSeenAllAnimals: 'Tüm hayvan dostları buldun!',
      startOver: 'Baştan Başla',
      menu: 'Menü',
      pickWorldMessage: 'Bir dünya seç ve macerana başla! 🐾',
      about: 'Oyun Hakkında',
      aboutDescription: 'Eğlenceye hazır mısın? Bu oyunda birbirinden sevimli hayvan dostlarla tanışacak ve çıkardıkları komik sesleri duyacaksın! Her hayvana dokun, adını ve sesini öğren. Möö! Vak vak! Kükreee!\n\nHepsini tanıyabilecek misin? Haydi birlikte oynayalım ve öğrenelim!',
      viewAllAnimals: 'Tüm Hayvan Dostlarını Gör',
      arcticCollection: 'Kutup Dostları Koleksiyonu',
      animalsToDiscover: 'Keşfedilecek {count} dost',
      missionComplete: '🏆 Görev Tamam!',
      missionNotebook: '{level} Görevi!',
      resetMissionTitle: 'Emin misin?',
      resetMissionMessage: 'Bu, bu görevdeki ilerlemeni sıfırlar.',
      yesReset: 'Evet, Sıfırla',
      resetMission: 'Görevi Sıfırla',
      animalLocked: 'Dost Kilitli!',
      unlockAnimalMessage: 'Bu dostu önce görevde keşfetmelisin.',
      cancel: 'İptal',
      goBack: 'Geri Dön',
      resetAllLevels: 'Tüm Görevleri Sıfırla',
      resetAllLevelsConfirmation: 'Tüm görev ilerlemesini sıfırlamak istediğine emin misin? Bu geri alınamaz.',
      reset: 'Sıfırla',
      resetComplete: 'Sıfırlandı!',
      allLevelsReset: 'Tüm görevler sıfırlandı, hadi baştan başlayalım!',
      error: 'Hata!',
      resetError: 'Bir şeyler ters gitti, tekrar dene.',
      gameProgress: 'Oyun Maceran',
      thankYou: 'Teşekkürler! 💖',
      allLevelsNowUnlocked: 'Artık tüm görevler açık!',
      purchaseError: 'Satın Alma Hatası',
      somethingWentWrong: 'Bir şeyler ters gitti.',
      restored: 'Geri Getirildi',
      noPreviousPurchases: 'Önceki satın alım bulunamadı.',
      noPurchasesFound: 'Önceki satın alım bulunamadı.',
      defaultPrice: '$0.99',
      discovered: 'Keşfedildi',
      levelDiscoveredAnimals: 'Hayvan dostları',
      levelDiscoveredInsects: 'Böcekler',
      levelDiscoveredBirds: 'Kuşlar',
        completeMission: 'Görevi Tamamla',
        completeMissionCelebration: '🎉 GÖREV TAMAMLANDI! 🎉',
        sound: 'Ses',
        dragAnimalHere: 'Hayvan dostunu buraya sürükle',
  
  
    animals: {
      cat: 'Kedi',
      chicken: 'Tavuk',
      dog: 'Köpek',
      donkey: 'Eşek',
      cow: 'İnek',
      chick: 'Civciv',
      leon: 'Aslan',
      duck: 'Ördek',
      goat: 'Keçi',
      goose: 'Kaz',
      horse: 'At',
      llama: 'Lama',
      pig: 'Domuz',
      rabbit: 'Tavşan',
      rooster: 'Horoz',
      sheep: 'Koyun',
      turkey: 'Hindi',
      fox: 'Tilki',
      bear: 'Ayı',
      whiteBear: 'Beyaz ayı',
      whiteFox: 'Kutup tilkisi',
      reindeer: 'Ren geyiği',
      snowyowl: 'Kar baykuşu',
      raccoon: 'Rakum',
      koala: 'Koala',
      squirrel: 'Sincap',
      hedgehog: 'Kirpi',
      owl: 'Baykuş',
      wolf: 'Kurt',
      deer: 'Geyik',
      moose: 'Alageyik',
      mouse: 'Fare',
      badger: 'Porsuk',
      beaver: 'Kunduz',
      boar: 'Yaban domuzu',
      bat: 'Yarasa',
      camel: 'Deve',
      crocodile: 'Timsah',
      dolphin: 'Yunus',
      eagle: 'Kartal',
      elephant: 'Fil',
      flamingo: 'Flamingo',
      frog: 'Kurbağa',
      giraffe: 'Zürafa',
      gorilla: 'Goril',
      hippopotamus: 'Su aygırı',
      leopard: 'Leopar',
      lion: 'Aslan',
      monkey: 'Maymun',
      octopus: 'Ahtapot',
      ostrich: 'Devekuşu',
      otter: 'Su samuru',
      panda: 'Panda',
      parrot: 'Papağan',
      peacock: 'Tavus kuşu',
      pelican: 'Pelikan',
      penguin: 'Penguen',
      rhinoceros: 'Gergedan',
      seal: 'Fok',
      mantis: 'Mantis',
      worm: 'Sürüngen',
      shark: 'Köpekbalığı',
      skunk: 'Kedi köpeği',
      snake: 'Yılan',
      tiger: 'Kaplan',
      turtle: 'Kaplumbağa',
      walrus: 'Deniz aygırı',
      whale: 'Balina',
      zebra: 'Zebra',
      ant: 'Karınca',
      bee: 'Arı',
      beetle: 'Böcek',
      butterfly: 'Kelebek',
      cricket: 'Cırcır böceği',
      dragonfly: 'Yusufçuk',
      firefly: 'Ateşböceği',
      fly: 'Sinek',
      grasshopper: 'Çekirge',
      ladybug: 'Uğur böceği',
      mosquito: 'Sivrisinek',
      scorpion: 'Akrep',
      snail: 'Salyangoz',
      spider: 'Örümcek',
      wasp: 'Eşek arısı',
      caracal: 'Karakal',
      desertTortoise: 'Çöl kaplumbağası',
      fennecFox: 'Fennek tilkisi',
      iguana: 'İguana',
      jackal: 'Çakal',
      jerboa: 'Çöl faresi',
      oryx: 'Oryx',
      sandCat: 'Kum kedisi',
      antelope: 'Antilop',
      bison: 'Bizon',
      gepard: 'Çita',
      hyena: 'Sırtlan',
      wildboar: 'Yaban domuzu',
      caterpillar: 'Tırtıl',
      cockroach: 'Hamam böceği',
      ladyBag: 'Uğur böceği',
      crab: 'Yengeç',
      fish: 'Balık',
      jellyfish: 'Denizanası',
      lobster: 'Istakoz',
      seaTurtle: 'Deniz kaplumbağası',
      seahorse: 'Denizatı',
      shrimp: 'Karides',
      starfish: 'Deniz yıldızı',
      stingray: 'Vatoz',
      canary: 'Kanarya',
      dove: 'Güvercin',
      raven: 'Kuzgun',
      seagull: 'Martı',
      sparrow: 'Serçe',
      stork: 'Leylek',
      swan: 'Kuğu',
      toucan: 'Tukan',
      woodpecker: 'Ağaçkakan',
      antEater: 'Karınca yiyen',
      asianElephant: 'Asya fili',
      bengalTiger: 'Bengal kaplanı',
      blackPanther: 'Siyah panter',
      capybara: 'Kapibara',
      chameleon: 'Bukalemun',
      cheetah: 'Çita',
      chimpanzee: 'Şempanze',
      cobra: 'Kobra',
      jaguar: 'Jaguar',
      lemur: 'Lemur',
      lynx: 'Vaşak',
      meerkat: 'Surikat',
      mongoose: 'Mangust',
      lizard: 'Kertenkele',
      orangutan: 'Orangutan',
      sloth: 'Tembel hayvan',
    },
  },
  // Add more languages here
};
