// app/localization/strings.ts

export const strings = {
  en: {
    selectLevel: 'Select language',
    farm: 'Farm',
    forest: 'Forest',
    ocean: 'Ocean',
    desert: 'Desert',
    arctic: 'Arctic',
    insects: 'Insects',
    savannah: 'Savannah',
    jungle: 'Jungle',
    birds: 'Birds',
    locked: 'Locked',
    tapToHear: 'Tap the animal to hear its sound!',
    unlockLevel: 'Unlock Level',
    unlockMessage: 'To unlock this level, you need to buy {level}.',
    appStorePay: 'Buy now',
    googlePlayPay: 'Buy now',
    backgroundNotAvailable: 'Background image not available for this level.',
    noAnimalsForLevel: 'No animals available for this level yet',
    tapAnimalToHearSound: 'Tap the animal to hear its sound!',
    levelFarm: 'LEVEL: FARM',
    levelForest: 'LEVEL: FOREST',
    levelOcean: 'LEVEL: OCEAN',
    levelDesert: 'LEVEL: DESERT',
    levelArctic: 'LEVEL: ARCTIC',
    levelInsects: 'LEVEL: INSECTS',
    levelSavannah: 'LEVEL: SAVANNAH',
    levelJungle: 'LEVEL: JUNGLE',
    levelBirds: 'LEVEL: BIRDS',
    unlockAllLevels: 'Unlock All Levels',
    restorePurchases: 'Restore Purchases',
    volume: 'Volume',
    language: 'Language',
    settings: 'Settings',
    selectLanguage: 'Select Language',
    close: 'Close',
    done: 'Done',
    thisLevelIsLocked: 'This level is locked. Unlock all levels to play!',
    unlockAllLevelsToPlay: 'Unlock All Levels To Play',
    skip: 'Skip',
    home: 'Home',
    congratulations: 'Congratulations!',
    youveSeenAllAnimals: "You've seen all the animals in this level!",
    startOver: 'Start Over',
    menu: 'Menu',
    pickWorldMessage: 'Pick a world and meet your new animal friends! 🐾',
    about: 'About',
    aboutDescription: 'Ready for some fun? In this game, you\'ll meet all kinds of animals — and hear the silly sounds they make! Just click or tap on each animal to hear its name and the noise it makes. Moo! Quack! Roar!\n\nCan you guess them all? Let\'s play and learn together!',
    animals: {
      cat: 'Cat',
      chicken: 'Chicken',
      dog: 'Dog',
      donkey: 'Donkey',
      cow: 'Cow',
      chick: 'Chick',
      duck: 'Duck',
      goat: 'Goat',
      goose: 'Goose',
      horse: 'Horse',
      llama: 'Llama',
      pig: 'Pig',
      rabbit: 'Rabbit',
      rooster: 'Rooster',
      sheep: 'Sheep',
      turkey: 'Turkey',
      fox: 'Fox',
      bear: 'Bear',
      whiteBear: 'White Bear',
      whiteFox: 'White Fox',
      reindeer: 'Reindeer',
      snowyowl: 'Snow Owl',
      raccoon: 'Raccoon',
      squirrel: 'Squirrel',
      hedgehog: 'Hedgehog',
      owl: 'Owl',
      wolf: 'Wolf',
      deer: 'Deer',
      moose: 'Moose',
      mouse: 'Mouse',
      badger: 'Badger',
      koala: 'Koala',
      beaver: 'Beaver',
      boar: 'Boar',
      bat: 'Bat',
      camel: 'Camel',
      leon: 'Lion',
      crocodile: 'Crocodile',
      dolphin: 'Dolphin',
      eagle: 'Eagle',
      elephant: 'Elephant',
      flamingo: 'Flamingo',
      frog: 'Frog',
      giraffe: 'Giraffe',
      gorilla: 'Gorilla',
      hippopotamus: 'Hippopotamus',
      leopard: 'Leopard',
      lion: 'Lion',
      monkey: 'Monkey',
      octopus: 'Octopus',
      ostrich: 'Ostrich',
      otter: 'Otter',
      panda: 'Panda',
      parrot: 'Parrot',
      peacock: 'Peacock',
      pelican: 'Pelican',
      penguin: 'Penguin',
      rhinoceros: 'Rhinoceros',
      seal: 'Seal',
      shark: 'Shark',
      snake: 'Snake',
      skunk: 'Skunk',
      tiger: 'Tiger',
      turtle: 'Turtle',
      walrus: 'Walrus',
      whale: 'Whale',
      zebra: 'Zebra',
      ant: 'Ant',
      bee: 'Bee',
      beetle: 'Beetle',
      butterfly: 'Butterfly',
      cricket: 'Cricket',
      dragonfly: 'Dragonfly',
      firefly: 'Firefly',
      fly: 'Fly',
      grasshopper: 'Grasshopper',
      ladybug: 'Ladybug',
      mosquito: 'Mosquito',
      scorpion: 'Scorpion',
      snail: 'Snail',
      spider: 'Spider',
      wasp: 'Wasp',
      caracal: 'Caracal',
      desertTortoise: 'Desert Tortoise',
      fennecFox: 'Fennec Fox',
      iguana: 'Iguana',
      jackal: 'Jackal',
      jerboa: 'Jerboa',
      oryx: 'Oryx',
      sandCat: 'Sand Cat',
      antelope: 'Antelope',
      bison: 'Bison',
      gepard: 'Cheetah',
      hyena: 'Hyena',
      wildboar: 'Wild Boar',
      caterpillar: 'Caterpillar',
      cockroach: 'Cockroach',
      ladyBag: 'Ladybug',
      crab: 'Crab',
      fish: 'Fish',
      jellyfish: 'Jellyfish',
      lobster: 'Lobster',
      seaTurtle: 'Sea Turtle',
      seahorse: 'Seahorse',
      shrimp: 'Shrimp',
      starfish: 'Starfish',
      stingray: 'Stingray',
      canary: 'Canary',
      dove: 'Dove',
      raven: 'Raven',
      seagull: 'Seagull',
      sparrow: 'Sparrow',
      stork: 'Stork',
      swan: 'Swan',
      toucan: 'Toucan',
      woodpecker: 'Woodpecker',
      antEater: 'Ant Eater',
      asianElephant: 'Asian Elephant',
      bengalTiger: 'Bengal Tiger',
      blackPanther: 'Black Panther',
      capybara: 'Capybara',
      chameleon: 'Chameleon',
      cheetah: 'Cheetah',
      chimpanzee: 'Chimpanzee',
      cobra: 'Cobra',
      jaguar: 'Jaguar',
      lemur: 'Lemur',
      lynx: 'Lynx',
      meerkat: 'Meerkat',
      mantis: 'Mantis',
      worm: 'Worm',
      mongoose: 'Mongoose',
      lizard: 'Lizard',
      orangutan: 'Orangutan',
      sloth: 'Sloth',
    },
  },
  ru: {
    selectLevel: 'Выберите язык',
    farm: 'Ферма',
    forest: 'Лес',
    ocean: 'Океан',
    desert: 'Пустыня',
    arctic: 'Арктика',
    insects: 'Насекомые',
    savannah: 'Саванна',
    jungle: 'Джунгли',
    birds: 'Птицы',
    locked: 'Заблокировано',
    tapToHear: 'Нажмите на животное, чтобы услышать его звук!',
    unlockLevel: 'Разблокировать уровень',
    unlockMessage: 'Чтобы разблокировать этот уровень, вам нужно купить {level}.',
    appStorePay: 'Купить сейчас(0.99$)',
    googlePlayPay: 'Купить сейчас(0.99$)',
    backgroundNotAvailable: 'Изображение фона не доступно для этого уровня.',
    noAnimalsForLevel: 'Нет животных для этого уровня.',
    tapAnimalToHearSound: 'Нажмите на животное, чтобы услышать его звук!',
    levelFarm: 'УРОВЕНЬ: ФЕРМА',
    levelForest: 'УРОВЕНЬ: ЛЕС',
    levelOcean: 'УРОВЕНЬ: ОКЕАН',
    levelDesert: 'УРОВЕНЬ: ПУСТЫНЯ',
    levelArctic: 'УРОВЕНЬ: АРКТИКА',
    levelInsects: 'УРОВЕНЬ: НАСЕКОМЫЕ',
    levelSavannah: 'УРОВЕНЬ: САВАННА',
    levelJungle: 'УРОВЕНЬ: ДЖУНГЛИ',
    levelBirds: 'УРОВЕНЬ: ПТИЦЫ',
    unlockAllLevels: 'Разблокировать все уровни',
    restorePurchases: 'Восстановить покупки',
    close: 'Закрыть',
    thisLevelIsLocked: 'Этот уровень заблокирован. Разблокируйте все уровни, чтобы играть!',
    unlockAllLevelsToPlay: 'Разблокировать все уровни',
    skip: 'Пропустить',
    home: 'Домой',
    volume: 'Громкость',
    done: 'Готово',
    language: 'Язык',
    settings: 'Настройки',
    selectLanguage: 'Выбрать язык',
    congratulations: 'Поздравляем!',
    youveSeenAllAnimals: 'Вы увидели всех животных на этом уровне!',
    startOver: 'Начать заново',
    menu: 'Меню',
    pickWorldMessage: 'Выберите мир и познакомьтесь с новыми друзьями-животными! 🐾',
    about: 'О игре',
    aboutDescription: 'Готовы к веселью? В этой игре вы встретите всех видов животных — и услышите забавные звуки, которые они издают! Просто нажмите на каждое животное, чтобы услышать его имя и звук, который оно издает. Му! Кря! Рычание!\n\nМожете ли вы угадать их всех? Давайте играть и учиться вместе!',
    animals: {
      cat: 'Кот',
      chicken: 'Курица',
      dog: 'Собака',
      donkey: 'Осел',
      cow: 'Корова',
      chick: 'Цыпленок',
      duck: 'Утка',
      goat: 'Коза',
      goose: 'Гусь',
      horse: 'Лошадь',
      llama: 'Лама',
      pig: 'Свинья',
      rabbit: 'Кролик',
      rooster: 'Петух',
      sheep: 'Овца',
      koala: 'Коала',
      turkey: 'Индейка',
      fox: 'Лиса',
      bear: 'Медведь',
      whiteBear: 'Белый медведь',
      whiteFox: 'Белая лиса',
      reindeer: 'Северный олень',
      snowyowl: 'Полярная сова',
      raccoon: 'Енот',
      squirrel: 'Белка',
      hedgehog: 'Ёж',
      owl: 'Сова',
      wolf: 'Волк',
      deer: 'Олень',
      moose: 'Лось',
      mouse: 'Мышь',
      badger: 'Барсук',
      beaver: 'Бобр',
      boar: 'Кабан',
      bat: 'Летучая мышь',
      camel: 'Верблюд',
      crocodile: 'Крокодил',
      dolphin: 'Дельфин',
      eagle: 'Орел',
      elephant: 'Слон',
      flamingo: 'Фламинго',
      frog: 'Лягушка',
      giraffe: 'Жираф',
      gorilla: 'Горилла',
      hippopotamus: 'Бегемот',
      leopard: 'Леопард',
      lion: 'Лев',
      monkey: 'Обезьяна',
      octopus: 'Осьминог',
      ostrich: 'Страус',
      otter: 'Выдра',
      panda: 'Панда',
      parrot: 'Попугай',
      peacock: 'Павлин',
      pelican: 'Пеликан',
      penguin: 'Пингвин',
      rhinoceros: 'Носорог',
      seal: 'Тюлень',
      shark: 'Акула',
      snake: 'Змея',
      skunk: 'Сурок',
      tiger: 'Тигр',
      turtle: 'Черепаха',
      walrus: 'Морж',
      whale: 'Кит',
      zebra: 'Зебра',
      ant: 'Муравей',
      bee: 'Пчела',
      beetle: 'Жук',
      butterfly: 'Бабочка',
      cricket: 'Сверчок',
      dragonfly: 'Стрекоза',
      firefly: 'Светлячок',
      fly: 'Муха',
      grasshopper: 'Кузнечик',
      ladybug: 'Божья коровка',
      mosquito: 'Комар',
      scorpion: 'Скорпион',
      snail: 'Улитка',
      spider: 'Паук',
      wasp: 'Оса',
      caracal: 'Каракал',
      desertTortoise: 'Пустынная черепаха',
      fennecFox: 'Фенек',
      iguana: 'Игуана',
      jackal: 'Шакал',
      mantis: 'Мантис',
      worm: 'Червь',
      jerboa: 'Тушканчик',
      oryx: 'Орикс',
      sandCat: 'Песчаная кошка',
      antelope: 'Антилопа',
      bison: 'Бизон',
      gepard: 'Гепард',
      hyena: 'Гиена',
      wildboar: 'Дикий кабан',
      caterpillar: 'Гусеница',
      cockroach: 'Таракан',
      ladyBag: 'Божья коровка',
      crab: 'Краб',
      fish: 'Рыба',
      leon: 'Лев',
      jellyfish: 'Медуза',
      lobster: 'Омар',
      seaTurtle: 'Морская черепаха',
      seahorse: 'Морской конек',
      shrimp: 'Креветка',
      starfish: 'Морская звезда',
      stingray: 'Скат',
      canary: 'Канарейка',
      dove: 'Голубь',
      raven: 'Ворон',
      seagull: 'Чайка',
      sparrow: 'Воробей',
      stork: 'Аист',
      swan: 'Лебедь',
      toucan: 'Тукан',
      woodpecker: 'Дятел',
      antEater: 'Муравьед',
      asianElephant: 'Азиатский слон',
      bengalTiger: 'Бенгальский тигр',
      blackPanther: 'Чёрная пантера',
      capybara: 'Капибара',
      chameleon: 'Хамелеон',
      cheetah: 'Гепард',
      chimpanzee: 'Шимпанзе',
      cobra: 'Кобра',
      jaguar: 'Ягуар',
      lemur: 'Лемур',
      lynx: 'Рысь',
      meerkat: 'Сурикат',
      mongoose: 'Мангуст',
      lizard: 'Ящерица',
      orangutan: 'Орангутан',
      sloth: 'Ленивец',
    },
  },
  tr: {
    selectLevel: 'Bir dil seçin',
    farm: 'Çiftlik',
    forest: 'Orman',
    ocean: 'Deniz',
    desert: 'Dağ',
    arctic: 'Kutup',
    insects: 'Böcek',
    savannah: 'Savannah',
    jungle: 'Jungle',
    birds: 'Kuş',
    locked: 'Kilitle',
    tapToHear: 'Hayvanın sesi için tıklayın!',
    unlockLevel: 'Seviye kilidini aç',
    unlockMessage: '{level} seviyesini açmak için {price} satın almalısınız.',
    appStorePay: 'Satın al',
    googlePlayPay: 'Satın al',
    backgroundNotAvailable: 'Bu seviye için arka plan resmi mevcut değil.',
    noAnimalsForLevel: 'Bu seviye için hayvan yok.',
    tapAnimalToHearSound: 'Hayvanın sesi için tıklayın!',
    levelFarm: 'SEVIYE: ÇİFTLİK',
    levelForest: 'SEVIYE: ORMAN',
    levelOcean: 'SEVIYE: DENİZ',
    levelDesert: 'SEVIYE: ÇÖLLÜK',
    levelArctic: 'SEVIYE: KUTUP',
    levelInsects: 'SEVIYE: BÖCEKLER',
    levelSavannah: 'SEVIYE: SAVAN',
    levelJungle: 'SEVIYE: ORMAN',
    levelBirds: 'SEVIYE: KUŞLAR',
    unlockAllLevels: 'Tüm Seviyeleri Aç',
    restorePurchases: 'Satın Alımları Geri Yükle',
    volume: 'Ses',
    done: 'Tamam',
    language: 'Dil',
    settings: 'Ayarlar',
    selectLanguage: 'Dil Seç',
    close: 'Kapat',
    thisLevelIsLocked: 'Bu seviye kilitli. Oynamak için tüm seviyeleri açın!',
    unlockAllLevelsToPlay: 'Tüm Seviyeleri Aç',
    skip: 'Atla',
    home: 'Ana Sayfa',
    congratulations: 'Tebrikler!',
    youveSeenAllAnimals: 'Bu seviyedeki tüm hayvanları gördünüz!',
    startOver: 'Yeniden Başla',
    menu: 'Menü',
    pickWorldMessage: 'Bir dünya seçin ve yeni hayvan arkadaşlarınızla tanışın! 🐾',
    about: 'Hakkında',
    aboutDescription: 'Eğlenceye hazır mısınız? Bu oyunda her türlü hayvanla tanışacak ve çıkardıkları komik sesleri duyacaksınız! Her hayvana tıklayarak ismini ve çıkardığı sesi duymak için tıklayın veya dokunun. Möö! Vak vak! Kükremeee!\n\nHepsini tahmin edebilir misiniz? Hadi birlikte oynayalım ve öğrenelim!',
    animals: {
      cat: 'Kedi',
      chicken: 'Tavuk',
      dog: 'Köpek',
      donkey: 'Eşek',
      cow: 'İnek',
      chick: 'Civciv',
      leon: 'Aslan',
      duck: 'Ördek',
      goat: 'Keçi',
      goose: 'Kaz',
      horse: 'At',
      llama: 'Lama',
      pig: 'Domuz',
      rabbit: 'Tavşan',
      rooster: 'Horoz',
      sheep: 'Koyun',
      turkey: 'Hindi',
      fox: 'Tilki',
      bear: 'Ayı',
      whiteBear: 'Beyaz ayı',
      whiteFox: 'Kutup tilkisi',
      reindeer: 'Ren geyiği',
      snowyowl: 'Kar baykuşu',
      raccoon: 'Rakum',
      koala: 'Koala',
      squirrel: 'Sincap',
      hedgehog: 'Kirpi',
      owl: 'Baykuş',
      wolf: 'Kurt',
      deer: 'Geyik',
      moose: 'Alageyik',
      mouse: 'Fare',
      badger: 'Porsuk',
      beaver: 'Kunduz',
      boar: 'Yaban domuzu',
      bat: 'Yarasa',
      camel: 'Deve',
      crocodile: 'Timsah',
      dolphin: 'Yunus',
      eagle: 'Kartal',
      elephant: 'Fil',
      flamingo: 'Flamingo',
      frog: 'Kurbağa',
      giraffe: 'Zürafa',
      gorilla: 'Goril',
      hippopotamus: 'Su aygırı',
      leopard: 'Leopar',
      lion: 'Aslan',
      monkey: 'Maymun',
      octopus: 'Ahtapot',
      ostrich: 'Devekuşu',
      otter: 'Su samuru',
      panda: 'Panda',
      parrot: 'Papağan',
      peacock: 'Tavus kuşu',
      pelican: 'Pelikan',
      penguin: 'Penguen',
      rhinoceros: 'Gergedan',
      seal: 'Fok',
      mantis: 'Mantis',
      worm: 'Sürüngen',
      shark: 'Köpekbalığı',
      skunk: 'Kedi köpeği',
      snake: 'Yılan',
      tiger: 'Kaplan',
      turtle: 'Kaplumbağa',
      walrus: 'Deniz aygırı',
      whale: 'Balina',
      zebra: 'Zebra',
      ant: 'Karınca',
      bee: 'Arı',
      beetle: 'Böcek',
      butterfly: 'Kelebek',
      cricket: 'Cırcır böceği',
      dragonfly: 'Yusufçuk',
      firefly: 'Ateşböceği',
      fly: 'Sinek',
      grasshopper: 'Çekirge',
      ladybug: 'Uğur böceği',
      mosquito: 'Sivrisinek',
      scorpion: 'Akrep',
      snail: 'Salyangoz',
      spider: 'Örümcek',
      wasp: 'Eşek arısı',
      caracal: 'Karakal',
      desertTortoise: 'Çöl kaplumbağası',
      fennecFox: 'Fennek tilkisi',
      iguana: 'İguana',
      jackal: 'Çakal',
      jerboa: 'Çöl faresi',
      oryx: 'Oryx',
      sandCat: 'Kum kedisi',
      antelope: 'Antilop',
      bison: 'Bizon',
      gepard: 'Çita',
      hyena: 'Sırtlan',
      wildboar: 'Yaban domuzu',
      caterpillar: 'Tırtıl',
      cockroach: 'Hamam böceği',
      ladyBag: 'Uğur böceği',
      crab: 'Yengeç',
      fish: 'Balık',
      jellyfish: 'Denizanası',
      lobster: 'Istakoz',
      seaTurtle: 'Deniz kaplumbağası',
      seahorse: 'Denizatı',
      shrimp: 'Karides',
      starfish: 'Deniz yıldızı',
      stingray: 'Vatoz',
      canary: 'Kanarya',
      dove: 'Güvercin',
      raven: 'Kuzgun',
      seagull: 'Martı',
      sparrow: 'Serçe',
      stork: 'Leylek',
      swan: 'Kuğu',
      toucan: 'Tukan',
      woodpecker: 'Ağaçkakan',
      antEater: 'Karınca yiyen',
      asianElephant: 'Asya fili',
      bengalTiger: 'Bengal kaplanı',
      blackPanther: 'Siyah panter',
      capybara: 'Kapibara',
      chameleon: 'Bukalemun',
      cheetah: 'Çita',
      chimpanzee: 'Şempanze',
      cobra: 'Kobra',
      jaguar: 'Jaguar',
      lemur: 'Lemur',
      lynx: 'Vaşak',
      meerkat: 'Surikat',
      mongoose: 'Mangust',
      lizard: 'Kertenkele',
      orangutan: 'Orangutan',
      sloth: 'Tembel hayvan',
    },
  },
  // Add more languages here
};
