// app/localization/strings.ts

export const strings = {
  en: {
    selectLevel: 'Select language',
    farm: 'Farm',
    forest: 'Forest',
    ocean: 'Ocean',
    desert: 'Desert',
    arctic: 'Arctic',
    insects: 'Insects',
    savannah: 'Savannah',
    jungle: 'Jungle',
    birds: 'Birds',
    locked: 'Locked',
    tapToHear: 'Tap the animal to hear its sound!',
    unlockLevel: 'Unlock Level',
    unlockMessage: 'To unlock this level, you need to buy {level}.',
    appStorePay: 'Buy now',
    googlePlayPay: 'Buy now',
    backgroundNotAvailable: 'Background image not available for this level.',
    noAnimalsForLevel: 'No animals available for this level yet',
    tapAnimalToHearSound: 'Tap the animal to hear its sound!',
    animals: {
      cat: 'Cat',
      chicken: 'Chicken',
      dog: 'Dog',
      donkey: 'Donkey',
      cow: 'Cow',
      chick: 'Chick',
      duck: 'Duck',
      goat: 'Goat',
      goose: 'Goose',
      horse: 'Horse',
      llama: 'Llama',
      pig: 'Pig',
      rabbit: 'Rabbit',
      rooster: 'Rooster',
      sheep: 'Sheep',
      turkey: 'Turkey',
      fox: 'Fox',
      bear: 'Bear',
      whiteBear: 'White Bear',
      whiteFox: 'White Fox',
      reindeer: 'Reindeer',
      snowyowl: 'Snow Owl',
      raccoon: 'Raccoon',
      squirrel: 'Squirrel',
      hedgehog: 'Hedgehog',
      owl: 'Owl',
      wolf: 'Wolf',
      deer: 'Deer',
      moose: 'Moose',
      mouse: 'Mouse',
      badger: 'Badger',
      beaver: 'Beaver',
      boar: 'Boar',
      bat: 'Bat',
      camel: 'Camel',
      crocodile: 'Crocodile',
      dolphin: 'Dolphin',
      eagle: 'Eagle',
      elephant: 'Elephant',
      flamingo: 'Flamingo',
      frog: 'Frog',
      giraffe: 'Giraffe',
      gorilla: 'Gorilla',
      hippopotamus: 'Hippopotamus',
      leopard: 'Leopard',
      lion: 'Lion',
      monkey: 'Monkey',
      octopus: 'Octopus',
      ostrich: 'Ostrich',
      otter: 'Otter',
      panda: 'Panda',
      parrot: 'Parrot',
      peacock: 'Peacock',
      pelican: 'Pelican',
      penguin: 'Penguin',
      rhinoceros: 'Rhinoceros',
      seal: 'Seal',
      shark: 'Shark',
      snake: 'Snake',
      tiger: 'Tiger',
      turtle: 'Turtle',
      walrus: 'Walrus',
      whale: 'Whale',
      zebra: 'Zebra',
      ant: 'Ant',
      bee: 'Bee',
      beetle: 'Beetle',
      butterfly: 'Butterfly',
      cricket: 'Cricket',
      dragonfly: 'Dragonfly',
      firefly: 'Firefly',
      fly: 'Fly',
      grasshopper: 'Grasshopper',
      ladybug: 'Ladybug',
      mosquito: 'Mosquito',
      scorpion: 'Scorpion',
      snail: 'Snail',
      spider: 'Spider',
      wasp: 'Wasp',
      caracal: 'Caracal',
      desertTortoise: 'Desert Tortoise',
      fennecFox: 'Fennec Fox',
      iguana: 'Iguana',
      jackal: 'Jackal',
      jerboa: 'Jerboa',
      oryx: 'Oryx',
      sandCat: 'Sand Cat',
      antelope: 'Antelope',
      bison: 'Bison',
      gepard: 'Cheetah',
      hyena: 'Hyena',
      wildboar: 'Wild Boar',
    },
  },
  ru: {
    selectLevel: 'Выберите язык',
    farm: 'Ферма',
    forest: 'Лес',
    ocean: 'Океан',
    desert: 'Пустыня',
    arctic: 'Арктика',
    insects: 'Насекомые',
    savannah: 'Саванна',
    jungle: 'Джунгли',
    birds: 'Птицы',
    locked: 'Заблокировано',
    tapToHear: 'Нажмите на животное, чтобы услышать его звук!',
    unlockLevel: 'Разблокировать уровень',
    unlockMessage: 'Чтобы разблокировать этот уровень, вам нужно купить {level}.',
    appStorePay: 'Купить сейчас(0.99$)',
    googlePlayPay: 'Купить сейчас(0.99$)',
    backgroundNotAvailable: 'Изображение фона не доступно для этого уровня.',
    noAnimalsForLevel: 'Нет животных для этого уровня.',
    tapAnimalToHearSound: 'Нажмите на животное, чтобы услышать его звук!',
    animals: {
      cat: 'Кот',
      chicken: 'Курица',
      dog: 'Собака',
      donkey: 'Осел',
      cow: 'Корова',
      chick: 'Цыпленок',
      duck: 'Утка',
      goat: 'Коза',
      goose: 'Гусь',
      horse: 'Лошадь',
      llama: 'Лама',
      pig: 'Свинья',
      rabbit: 'Кролик',
      rooster: 'Петух',
      sheep: 'Овца',
      turkey: 'Индейка',
      fox: 'Лиса',
      bear: 'Медведь',
      whiteBear: 'Белый медведь',
      whiteFox: 'Белая лиса',
      reindeer: 'Северный олень',
      snowyowl: 'Полярная сова',
      raccoon: 'Енот',
      squirrel: 'Белка',
      hedgehog: 'Ёж',
      owl: 'Сова',
      wolf: 'Волк',
      deer: 'Олень',
      moose: 'Лось',
      mouse: 'Мышь',
      badger: 'Барсук',
      beaver: 'Бобр',
      boar: 'Кабан',
      bat: 'Летучая мышь',
      camel: 'Верблюд',
      crocodile: 'Крокодил',
      dolphin: 'Дельфин',
      eagle: 'Орел',
      elephant: 'Слон',
      flamingo: 'Фламинго',
      frog: 'Лягушка',
      giraffe: 'Жираф',
      gorilla: 'Горилла',
      hippopotamus: 'Бегемот',
      leopard: 'Леопард',
      lion: 'Лев',
      monkey: 'Обезьяна',
      octopus: 'Осьминог',
      ostrich: 'Страус',
      otter: 'Выдра',
      panda: 'Панда',
      parrot: 'Попугай',
      peacock: 'Павлин',
      pelican: 'Пеликан',
      penguin: 'Пингвин',
      rhinoceros: 'Носорог',
      seal: 'Тюлень',
      shark: 'Акула',
      snake: 'Змея',
      tiger: 'Тигр',
      turtle: 'Черепаха',
      walrus: 'Морж',
      whale: 'Кит',
      zebra: 'Зебра',
      ant: 'Муравей',
      bee: 'Пчела',
      beetle: 'Жук',
      butterfly: 'Бабочка',
      cricket: 'Сверчок',
      dragonfly: 'Стрекоза',
      firefly: 'Светлячок',
      fly: 'Муха',
      grasshopper: 'Кузнечик',
      ladybug: 'Божья коровка',
      mosquito: 'Комар',
      scorpion: 'Скорпион',
      snail: 'Улитка',
      spider: 'Паук',
      wasp: 'Оса',
      caracal: 'Каракал',
      desertTortoise: 'Пустынная черепаха',
      fennecFox: 'Фенек',
      iguana: 'Игуана',
      jackal: 'Шакал',
      jerboa: 'Тушканчик',
      oryx: 'Орикс',
      sandCat: 'Песчаная кошка',
      antelope: 'Антилопа',
      bison: 'Бизон',
      gepard: 'Гепард',
      hyena: 'Гиена',
      wildboar: 'Дикий кабан',
    },
  },
  es: {
    selectLevel: 'Selecciona un idioma',
    farm: 'Granja',
    forest: 'Bosque',
    ocean: 'Oceano',
    desert: 'Desierto',
    arctic: 'Arctico',
    insects: 'Insectos',
    savannah: 'Savannah',
    jungle: 'Jungle',
    birds: 'Pájaros',
    locked: 'Bloqueado',
    tapToHear: 'Toca en el animal para escuchar su sonido!',
    unlockLevel: 'Desbloquear nivel',
    unlockMessage: 'Para desbloquear este nivel, necesitas comprar {level}.',
    appStorePay: 'Comprar ahora',
    googlePlayPay: 'Comprar ahora',
    backgroundNotAvailable: 'Imagen de fondo no disponible para este nivel.',
    noAnimalsForLevel: 'No hay animales disponibles para este nivel.',
    tapAnimalToHearSound: 'Toca en el animal para escuchar su sonido!',
    animals: {
      cat: 'Gato',
      chicken: 'Gallina',
      dog: 'Perro',
      donkey: 'Burro',
      cow: 'Vaca',
      chick: 'Pollito',
      duck: 'Pato',
      goat: 'Cabra',
      goose: 'Ganso',
      horse: 'Caballo',
      llama: 'Llama',
      pig: 'Cerdo',
      rabbit: 'Conejo',
      rooster: 'Gallo',
      sheep: 'Oveja',
      turkey: 'Pavo',
      fox: 'Zorro',
      bear: 'Oso',
      whiteBear: 'Oso blanco',
      whiteFox: 'Zorro ártico',
      reindeer: 'Reno',
      snowyowl: 'Búho nival',
      raccoon: 'Mapache',
      squirrel: 'Ardilla',
      hedgehog: 'Erizo',
      owl: 'Búho',
      wolf: 'Lobo',
      deer: 'Ciervo',
      moose: 'Alce',
      mouse: 'Ratón',
      badger: 'Tejón',
      beaver: 'Castor',
      boar: 'Jabalí',
      bat: 'Murciélago',
      camel: 'Camello',
      crocodile: 'Cocodrilo',
      dolphin: 'Delfín',
      eagle: 'Águila',
      elephant: 'Elefante',
      flamingo: 'Flamenco',
      frog: 'Rana',
      giraffe: 'Jirafa',
      gorilla: 'Gorila',
      hippopotamus: 'Hipopótamo',
      leopard: 'Leopardo',
      lion: 'León',
      monkey: 'Mono',
      octopus: 'Pulpo',
      ostrich: 'Avestruz',
      otter: 'Nutria',
      panda: 'Panda',
      parrot: 'Loro',
      peacock: 'Pavo real',
      pelican: 'Pelícano',
      penguin: 'Pingüino',
      rhinoceros: 'Rinoceronte',
      seal: 'Foca',
      shark: 'Tiburón',
      snake: 'Serpiente',
      tiger: 'Tigre',
      turtle: 'Tortuga',
      walrus: 'Morsa',
      whale: 'Ballena',
      zebra: 'Cebra',
      ant: 'Hormiga',
      bee: 'Abeja',
      beetle: 'Escarabajo',
      butterfly: 'Mariposa',
      cricket: 'Grillo',
      dragonfly: 'Libélula',
      firefly: 'Luciérnaga',
      fly: 'Mosca',
      grasshopper: 'Saltamontes',
      ladybug: 'Mariquita',
      mosquito: 'Mosquito',
      scorpion: 'Escorpión',
      snail: 'Caracol',
      spider: 'Araña',
      wasp: 'Avispa',
      caracal: 'Caracal',
      desertTortoise: 'Tortuga del desierto',
      fennecFox: 'Zorro fénec',
      iguana: 'Iguana',
      jackal: 'Chacal',
      jerboa: 'Jerbo',
      oryx: 'Órix',
      sandCat: 'Gato del desierto',
      antelope: 'Antílope',
      bison: 'Bisonte',
      gepard: 'Guepardo',
      hyena: 'Hiena',
      wildboar: 'Jabalí salvaje',
    },
  },
  de: {
    selectLevel: 'Wähle einen Sprache',
    farm: 'Farm',
    forest: 'Wald',
    ocean: 'Ozean',
    desert: 'Wüste',
    arctic: 'Arktis',
    insects: 'Insekten',
    savannah: 'Savannah',
    jungle: 'Jungle',
    birds: 'Vögel',
    locked: 'Gesperrt',
    tapToHear: 'Tippe auf das Tier, um seinen Sound zu hören!',
    unlockLevel: 'Level freischalten',
    unlockMessage: 'Um dieses Level freizuschalten, müssen Sie {level} kaufen.',
    appStorePay: 'Jetzt kaufen',
    googlePlayPay: 'Jetzt kaufen',
    backgroundNotAvailable: 'Hintergrundbild nicht verfügbar für dieses Level.',
    noAnimalsForLevel: 'Keine Tiere verfügbar für dieses Level.',
    tapAnimalToHearSound: 'Tippe auf das Tier, um seinen Sound zu hören!',
    animals: {
      cat: 'Katze',
      chicken: 'Huhn',
      dog: 'Hund',
      donkey: 'Esel',
      cow: 'Kuh',
      chick: 'Küken',
      duck: 'Ente',
      goat: 'Ziege',
      goose: 'Gans',
      horse: 'Pferd',
      llama: 'Lama',
      pig: 'Schwein',
      rabbit: 'Kaninchen',
      rooster: 'Hahn',
      sheep: 'Schaf',
      turkey: 'Truthahn',
      fox: 'Fuchs',
      bear: 'Bär',
      whiteBear: 'Eisbär',
      whiteFox: 'Polarfuchs',
      reindeer: 'Rentier',
      snowyowl: 'Schnee-Eule',
      raccoon: 'Waschbär',
      squirrel: 'Eichhörnchen',
      hedgehog: 'Igel',
      owl: 'Eule',
      wolf: 'Wolf',
      deer: 'Hirsch',
      moose: 'Elch',
      mouse: 'Maus',
      badger: 'Dachs',
      beaver: 'Biber',
      boar: 'Wildschwein',
      bat: 'Fledermaus',
      camel: 'Kamel',
      crocodile: 'Krokodil',
      dolphin: 'Delfin',
      eagle: 'Adler',
      elephant: 'Elefant',
      flamingo: 'Flamingo',
      frog: 'Frosch',
      giraffe: 'Giraffe',
      gorilla: 'Gorilla',
      hippopotamus: 'Nilpferd',
      leopard: 'Leopard',
      lion: 'Löwe',
      monkey: 'Affe',
      octopus: 'Oktopus',
      ostrich: 'Strauß',
      otter: 'Otter',
      panda: 'Panda',
      parrot: 'Papagei',
      peacock: 'Pfau',
      pelican: 'Pelikan',
      penguin: 'Pinguin',
      rhinoceros: 'Nashorn',
      seal: 'Seehund',
      shark: 'Hai',
      snake: 'Schlange',
      tiger: 'Tiger',
      turtle: 'Schildkröte',
      walrus: 'Walross',
      whale: 'Wal',
      zebra: 'Zebra',
      ant: 'Ameise',
      bee: 'Biene',
      beetle: 'Käfer',
      butterfly: 'Schmetterling',
      cricket: 'Grille',
      dragonfly: 'Libelle',
      firefly: 'Glühwürmchen',
      fly: 'Fliege',
      grasshopper: 'Heuschrecke',
      ladybug: 'Marienkäfer',
      mosquito: 'Mücke',
      scorpion: 'Skorpion',
      snail: 'Schnecke',
      spider: 'Spinne',
      wasp: 'Wespe',
      caracal: 'Karakal',
      desertTortoise: 'Wüstenschildkröte',
      fennecFox: 'Fennek',
      iguana: 'Leguan',
      jackal: 'Schakal',
      jerboa: 'Springmaus',
      oryx: 'Oryx',
      sandCat: 'Sandkatze',
      antelope: 'Antilope',
      bison: 'Bison',
      gepard: 'Gepard',
      hyena: 'Hyäne',
      wildboar: 'Wildschwein',
    },
  },
  fr: {
    selectLevel: 'Choisissez un langage',
    farm: 'Ferme',
    forest: 'Forêt',
    ocean: 'Océan',
    desert: 'Desert',
    arctic: 'Arctique',
    insects: 'Insectes',
    savannah: 'Savannah',
    jungle: 'Jungle',
    birds: 'Oiseaux',
    locked: 'Bloqué',
    tapToHear: 'Tapez sur l\'animal pour entendre son son!',
    unlockLevel: 'Niveau débloqué',
    unlockMessage: 'Pour débloquer ce niveau, vous devez acheter {level}.',
    appStorePay: 'Acheter maintenant',
    googlePlayPay: 'Acheter maintenant',
    backgroundNotAvailable: 'Image de fond non disponible pour ce niveau.',
    noAnimalsForLevel: 'Aucun animal disponible pour ce niveau.',
    tapAnimalToHearSound: 'Tapez sur l\'animal pour entendre son son!',
    animals: {
      cat: 'Chat',
      chicken: 'Poulet',
      dog: 'Chien',
      donkey: 'Âne',
      cow: 'Vache',
      chick: 'Poussin',
      duck: 'Canard',
      goat: 'Chèvre',
      goose: 'Oie',
      horse: 'Cheval',
      llama: 'Lama',
      pig: 'Cochon',
      rabbit: 'Lapin',
      rooster: 'Coq',
      sheep: 'Mouton',
      turkey: 'Dinde',
      fox: 'Renard',
      bear: 'Ours',
      whiteBear: 'Ours blanc',
      whiteFox: 'Renard polaire',
      reindeer: 'Renne',
      snowyowl: 'Harfang des neiges',
      raccoon: 'Raton laveur',
      squirrel: 'Écureuil',
      hedgehog: 'Hérisson',
      owl: 'Hibou',
      wolf: 'Loup',
      deer: 'Cerf',
      moose: 'Élan',
      mouse: 'Souris',
      badger: 'Blaireau',
      beaver: 'Castor',
      boar: 'Sanglier',
      bat: 'Chauve-souris',
      camel: 'Chameau',
      crocodile: 'Crocodile',
      dolphin: 'Dauphin',
      eagle: 'Aigle',
      elephant: 'Éléphant',
      flamingo: 'Flamant rose',
      frog: 'Grenouille',
      giraffe: 'Girafe',
      gorilla: 'Gorille',
      hippopotamus: 'Hippopotame',
      leopard: 'Léopard',
      lion: 'Lion',
      monkey: 'Singe',
      octopus: 'Poulpe',
      ostrich: 'Autruche',
      otter: 'Loutre',
      panda: 'Panda',
      parrot: 'Perroquet',
      peacock: 'Paon',
      pelican: 'Pélican',
      penguin: 'Manchot',
      rhinoceros: 'Rhinocéros',
      seal: 'Phoque',
      shark: 'Requin',
      snake: 'Serpent',
      tiger: 'Tigre',
      turtle: 'Tortue',
      walrus: 'Morse',
      whale: 'Baleine',
      zebra: 'Zèbre',
      ant: 'Fourmi',
      bee: 'Abeille',
      beetle: 'Scarabée',
      butterfly: 'Papillon',
      cricket: 'Grillon',
      dragonfly: 'Libellule',
      firefly: 'Luciole',
      fly: 'Mouche',
      grasshopper: 'Sauterelle',
      ladybug: 'Coccinelle',
      mosquito: 'Moustique',
      scorpion: 'Scorpion',
      snail: 'Escargot',
      spider: 'Araignée',
      wasp: 'Guêpe',
      caracal: 'Caracal',
      desertTortoise: 'Tortue du désert',
      fennecFox: 'Fennec',
      iguana: 'Iguane',
      jackal: 'Chacal',
      jerboa: 'Gerboise',
      oryx: 'Oryx',
      sandCat: 'Chat des sables',
      antelope: 'Antilope',
      bison: 'Bison',
      gepard: 'Guépard',
      hyena: 'Hyène',
      wildboar: 'Sanglier sauvage',
    },
  },
  it: {
    selectLevel: 'Scegli un livello',
    farm: 'Fattoria',
    forest: 'Foresta',
    ocean: 'Oceano',
    desert: 'Deserto',
    arctic: 'Artico',
    insects: 'Insetti',
    savannah: 'Savannah',
    jungle: 'Jungle',
    birds: 'Uccelli',
    locked: 'Bloccato',
    tapToHear: 'Toca l\'animale per sentire il suo suono!',
    unlockLevel: 'Livello sbloccato',
    unlockMessage: 'Per sbloccare questo livello, devi comprare {level}.',
    appStorePay: 'Comprare ora',
    googlePlayPay: 'Comprare ora',
    backgroundNotAvailable: 'Immagine di sfondo non disponibile per questo livello.',
    noAnimalsForLevel: 'Nessun animale disponibile per questo livello.',
    tapAnimalToHearSound: 'Toca l\'animale per sentire il suo suono!',
    animals: {
      cat: 'Gatto',
      chicken: 'Pollo',
      dog: 'Cane',
      donkey: 'Asino',
      cow: 'Mucca',
      chick: 'Pulcino',
      duck: 'Anatra',
      goat: 'Capra',
      goose: 'Oca',
      horse: 'Cavallo',
      llama: 'Lama',
      pig: 'Maiale',
      rabbit: 'Coniglio',
      rooster: 'Gallo',
      sheep: 'Pecora',
      turkey: 'Tacchino',
      fox: 'Volpe',
      bear: 'Orso',
      whiteBear: 'Orso bianco',
      whiteFox: 'Volpe artica',
      reindeer: 'Renna',
      snowyowl: 'Civetta delle nevi',
      raccoon: 'Procione',
      squirrel: 'Scoiattolo',
      hedgehog: 'Riccio',
      owl: 'Gufo',
      wolf: 'Lupo',
      deer: 'Cervo',
      moose: 'Alce',
      mouse: 'Topo',
      badger: 'Tasso',
      beaver: 'Castoro',
      boar: 'Cinghiale',
      bat: 'Pipistrello',
      camel: 'Cammello',
      crocodile: 'Coccodrillo',
      dolphin: 'Delfino',
      eagle: 'Aquila',
      elephant: 'Elefante',
      flamingo: 'Fenicottero',
      frog: 'Rana',
      giraffe: 'Giraffa',
      gorilla: 'Gorilla',
      hippopotamus: 'Ippopotamo',
      leopard: 'Leopardo',
      lion: 'Leone',
      monkey: 'Scimmia',
      octopus: 'Polpo',
      ostrich: 'Struzzo',
      otter: 'Lontra',
      panda: 'Panda',
      parrot: 'Pappagallo',
      peacock: 'Pavone',
      pelican: 'Pellicano',
      penguin: 'Pinguino',
      rhinoceros: 'Rinoceronte',
      seal: 'Foca',
      shark: 'Squalo',
      snake: 'Serpente',
      tiger: 'Tigre',
      turtle: 'Tartaruga',
      walrus: 'Tricheco',
      whale: 'Balena',
      zebra: 'Zebra',
      ant: 'Formica',
      bee: 'Ape',
      beetle: 'Scarabeo',
      butterfly: 'Farfalla',
      cricket: 'Grillo',
      dragonfly: 'Libellula',
      firefly: 'Lucciola',
      fly: 'Mosca',
      grasshopper: 'Cavalletta',
      ladybug: 'Coccinella',
      mosquito: 'Zanzara',
      scorpion: 'Scorpione',
      snail: 'Lumaca',
      spider: 'Ragno',
      wasp: 'Vespa',
      caracal: 'Caracal',
      desertTortoise: 'Tartaruga del deserto',
      fennecFox: 'Fennec',
      iguana: 'Iguana',
      jackal: 'Sciacallo',
      jerboa: 'Gerboa',
      oryx: 'Oryx',
      sandCat: 'Gatto delle sabbie',
      antelope: 'Antilope',
      bison: 'Bisonte',
      gepard: 'Ghepardo',
      hyena: 'Iena',
      wildboar: 'Cinghiale selvatico',
    },
  },
  tr: {
    selectLevel: 'Bir dil seçin',
    farm: 'Çiftlik',
    forest: 'Orman',
    ocean: 'Deniz',
    desert: 'Dağ',
    arctic: 'Kutup',
    insects: 'Böcek',
    savannah: 'Savannah',
    jungle: 'Jungle',
    birds: 'Kuş',
    locked: 'Kilitle',
    tapToHear: 'Hayvanın sesi için tıklayın!',
    unlockLevel: 'Seviye kilidini aç',
    unlockMessage: '{level} seviyesini açmak için {price} satın almalısınız.',
    appStorePay: 'Satın al',
    googlePlayPay: 'Satın al',
    backgroundNotAvailable: 'Bu seviye için arka plan resmi mevcut değil.',
    noAnimalsForLevel: 'Bu seviye için hayvan yok.',
    tapAnimalToHearSound: 'Hayvanın sesi için tıklayın!',
    animals: {
      cat: 'Kedi',
      chicken: 'Tavuk',
      dog: 'Köpek',
      donkey: 'Eşek',
      cow: 'İnek',
      chick: 'Civciv',
      duck: 'Ördek',
      goat: 'Keçi',
      goose: 'Kaz',
      horse: 'At',
      llama: 'Lama',
      pig: 'Domuz',
      rabbit: 'Tavşan',
      rooster: 'Horoz',
      sheep: 'Koyun',
      turkey: 'Hindi',
      fox: 'Tilki',
      bear: 'Ayı',
      whiteBear: 'Beyaz ayı',
      whiteFox: 'Kutup tilkisi',
      reindeer: 'Ren geyiği',
      snowyowl: 'Kar baykuşu',
      raccoon: 'Rakum',
      squirrel: 'Sincap',
      hedgehog: 'Kirpi',
      owl: 'Baykuş',
      wolf: 'Kurt',
      deer: 'Geyik',
      moose: 'Alageyik',
      mouse: 'Fare',
      badger: 'Porsuk',
      beaver: 'Kunduz',
      boar: 'Yaban domuzu',
      bat: 'Yarasa',
      camel: 'Deve',
      crocodile: 'Timsah',
      dolphin: 'Yunus',
      eagle: 'Kartal',
      elephant: 'Fil',
      flamingo: 'Flamingo',
      frog: 'Kurbağa',
      giraffe: 'Zürafa',
      gorilla: 'Goril',
      hippopotamus: 'Su aygırı',
      leopard: 'Leopar',
      lion: 'Aslan',
      monkey: 'Maymun',
      octopus: 'Ahtapot',
      ostrich: 'Devekuşu',
      otter: 'Su samuru',
      panda: 'Panda',
      parrot: 'Papağan',
      peacock: 'Tavus kuşu',
      pelican: 'Pelikan',
      penguin: 'Penguen',
      rhinoceros: 'Gergedan',
      seal: 'Fok',
      shark: 'Köpekbalığı',
      snake: 'Yılan',
      tiger: 'Kaplan',
      turtle: 'Kaplumbağa',
      walrus: 'Deniz aygırı',
      whale: 'Balina',
      zebra: 'Zebra',
      ant: 'Karınca',
      bee: 'Arı',
      beetle: 'Böcek',
      butterfly: 'Kelebek',
      cricket: 'Cırcır böceği',
      dragonfly: 'Yusufçuk',
      firefly: 'Ateşböceği',
      fly: 'Sinek',
      grasshopper: 'Çekirge',
      ladybug: 'Uğur böceği',
      mosquito: 'Sivrisinek',
      scorpion: 'Akrep',
      snail: 'Salyangoz',
      spider: 'Örümcek',
      wasp: 'Eşek arısı',
      caracal: 'Karakal',
      desertTortoise: 'Çöl kaplumbağası',
      fennecFox: 'Fennek tilkisi',
      iguana: 'İguana',
      jackal: 'Çakal',
      jerboa: 'Çöl faresi',
      oryx: 'Oryx',
      sandCat: 'Kum kedisi',
      antelope: 'Antilop',
      bison: 'Bizon',
      gepard: 'Çita',
      hyena: 'Sırtlan',
      wildboar: 'Yaban domuzu',
    },
  },
  // Add more languages here
};
